<?php

namespace frontend\controllers;

use common\models\OrderInfo;
use frontend\components\AjaxReturn;
use frontend\models\Cart;
use frontend\models\Payment;
use frontend\models\Region;
use frontend\models\UserAddress;
use yii;
use common\models\Category;

class OrderController extends \yii\web\Controller
{

    public $userId;
    public $layout = 'navmain';

    public function init()
    {
        // 验证是否登录
        if(Yii::$app->user->isGuest)
        {
            return $this->goBack();
        }
        $this->userId = Yii::$app->user->getId();
    }

    public function behaviors()
    {

        // 查询主导航
        $navigation = Category::getNavigation();
        $this->view->params['navigation'] = $navigation;

        return parent::behaviors(); // TODO: Change the autogenerated stub

    }

    /**
     * 下单
     * @return string
     */
    public function actionCheckout()
    {

        // 判断是否有收货地址
        if(!$address = UserAddress::getAddress($this->userId))
        {
            yii::$app->response->redirect(['order/consignee']);
        }


        // 查询购物车商品
        $cart = Cart::getCartList();
        if(count($cart['goodsList']) == 0)
        {
            $this->goBack();
        }

        // 查询支付方式
        $paies = Payment::getPay();

        return $this->render('checkout',['address'=>$address,'cart'=>$cart,'paies'=>$paies]);
    }

    /**
     * 填写收货信息
     *
     * @return string
     */
    public function actionConsignee()
    {
        $model = new UserAddress();

        if(yii::$app->request->isPost)
        {
            $model->user_id = $this->userId;
            if($model->load(yii::$app->request->post()) && $model->validate())
            {
                $result = $model->save();
                if($result)
                {
                    yii::$app->response->redirect(['order/checkout']);
                }
                else
                {
                    echo 'save faill';
                }
            }
        }

        $region = Region::getDropDownRegion();
        var_dump($region);
        return $this->render('consignee',['userAdd'=>$model,'region'=>$region]);
    }


    /**
     * 下单
     */
    public function actionOrderDown()
    {
        $aid = Yii::$app->request->get('aid');
        $pid = Yii::$app->request->get('pid');
        $orderInfo = [];

        // 支付方式
        $pay = Payment::getPayInfo($pid);

        // 选中的收获地址
        $address = UserAddress::getInfo($aid);

        // 订单商品与金额
        $cart = Cart::getCartList();

        // 生产订单号
        $orderInfo['order_sn'] = OrderInfo::createOrderSn();

        // 下单
        $result = (new OrderInfo)->createOrder(array_merge($orderInfo,$address,$cart,$pay));

        // 清除购物车
        Cart::clearAll();

        // 响应
        $result->send();
    }

    public function actionAlipay()
    {
        $get = Yii::$app->request->get();
        var_dump($get);
    }

}
